cache: yarn
env:
  global:
  - AWS_DEFAULT_REGION="eu-west-1"
  - AWS_BUCKET_NAME="terraformapply.com"
language: node_js
node_js:
- lts/*
script: yarn build
after_success:
  - pip install --user awscli
  - aws s3 cp dist s3://$AWS_BUCKET_NAME/ --recursive
