cache: yarn
env:
  global:
  - AWS_REGION="eu-west-1"
  - AWS_BUCKET_NAME="terraformapply.com"
  # AWS_ACCESS_KEY_ID
  secure: "X28IowiraZCy/YxUXV3HM/3Z4C6mselmS2RRWfJa1DPGttQbFuhjoeBckUGGckBQKVJjPHIW5rqlr1mbagE7Ul+/0/2gpnhRAFmDvlJ22XNvq0m3yZgrdJXjsNg0AFhnQTdlOUSOdo8tnym1dF4XK2+N81k3jKlvly3GvhhGmqBdSXXfUf6XAQndfNfhmqawRFIOz85DvFH5BwYWMTAQ8kLLY8k4gDF+2tRsnwd0TLvf1+e/4Mp1HVj50X6phHkrcvwNyctBYCQfLWmoADh9SZZ+0VIC99a444c+OI6JeSPJ6T2OMqbRIv5AxFW8pDEsvKyEPlj2+AeugSVIqFN2yaiCpNyFX8dkdCuXMvPUgM/VD4uXQsLA85Qhh+AA2Jeu1nV+WtUBRS4Ghfm5rupWam3s/niZjq1LrGWb9yzA/+zHYSsObgB9srBtnjS/MNdYkLanID65bie+PPW4Cy7ps7QA6mj+OX1UOPfyTgscKk1RxuQjG+dwZ2+p4jY4TTGaYBky7H5EmqmQ+TQdyxN3A3uuEKYUCY7Vnu/4n2UyBUdx7Ko99SlQMV5AuZJZgHZoike7pEBhos6SjCJlZjClMdQTu4hVyHl5Ect8fdMg4/yjVMIZpUHVERddgjVGI7ltxW0QeGdJILJQ0des5vWD+JjTxQ6X2XN8dljKPQAGfsA="
  # AWS_SECRET_ACCESS_KEY
  secure: "iqyDH+MlvKFJmxYCDn4WU33bp526M5JFdSITvVT5lvqjjo5JGpfbOFXDM9suYxm8QGlawsIbQY6wJ0V0GY7grQgaZcED5euoU02l/7dLPjDpN2BgUQxvaKGppV5Q0AxP//GH47fMFeV3KoLovDn69h2EshBZR4R0TfowKJIwZQh+TlR7ofhf78cJu1KcopP3m0ysD50SSDIaDigsfRbYYGa8A4MPL+I7f7kx6b5PGNfbVacaUYyW6Oyrg6QeKz8EfiPeSN4grmjAMnL8nGi9K5vzb0MKE0mDEvZbgWhdCwb13yI3oaA9QSdhrOHXnKYt8gdcspdZOwCfiN0jctBDlYjM8HcXCdZRM4soFSfsfti/fNezVEM01Zixli8E5FnCumjor2y4Yt1e78g/33i7ilbdkZtqAxQX2vQw8YOljVxvs3RopBjc1vkJJj0hpCcG6+TAA5nWWyMV0aNpsuBQbNswxjutGfI22Smhgw2dT+V2a6IViTOHJWOiFSbmn4/xRBWhSlIlFbif30PRQkBORJ4zTYYcgVIFzMi6rS8q5QL/f/XGXqA4Jp+7syBwAOvcyEtezPRHJh1XY21QX6Noalu+axHeYlIjhKV3rVYA5wV6nKdkIz2sNrsRrIlJcCi8x2DJH15cgQ5RVE9vuZKozeCkGLKmTylalQ7vHZA4Nbg="
language: node_js
node_js:
- lts/*
script: yarn build
after_success:
  - pip install --user awscli
  - aws s3 cp dist s3://$AWS_BUCKET_NAME/ --recursive
