language: node_js
node_js:
- lts/*
cache: yarn
script: yarn build
deploy:
  provider: s3
  access_key_id:
    secure: BxfuVbCySQaDF5H1RNrwqNT2GngqoTHIJW/MJAVziko9fg+0VXzPj5qcPcssvkhffHNRqAg42OCRDbN6NpcO6RW8rUbCP/2ZFcBIo4uxGR4UFN6VMjBZMx8JWv4AFbGB8mupdwBx/YIEXbd0GrcbmBjSi/Y6upe8QQfk8r4svNlp1f41vFYJ5jZlFU0y8Nx7JLGfCp5Oj55iBI9XiNJr6cXh/+VIVSgZ+IJNnY3ks3y8ApCC1roPgv17F/5Hml66sZqNBQys4gaYoneWw6DCyt0nYe7yplu52oxnAtVYVsnftY8Ho4g/QKKJ13bKvzcIrMQvhytWs/1OFs7rMITBcVjaprkgdog808GdxUBgaHxGcJ2gmOagjhiMG8pduchA0r+fjg3oX9nFQIBKQ+ofFnYLSkI1oLkLwdjlHWGm+hIYRTSQ7YzHJ8PRbmhz9FquGoVouo2F4/+gD0WHd79ewkxi9WpMOyKeiuWDk8ETMPq4I6QLzzGGrTiX37aXPfJXQoZij4lLyn+T/Kjwy4orS+XaKS9WXYbwIvOy1NG9EWElnob4q/D9qpq38tK3mpWNZ/slVGX07s4hbzPfqD+p2KP7mVYR/yTsUA5g+5UhMm4fGrIFHKMRY1+hqbl1HWYB7edcjpfarK5R0uN2WdyEJYy3KlvGf8uaN66X8ceWdNQ=
  secret_access_key:
    secure: bx9To0BpwOSft0w5fl9fL56qs24bCelLCHoDGR42Tl/8Spm81LRNWJ4Z0WZ05dPaYw7DDwxv9+wtjkw3Wx8ykonyupIWFWZnkDeM1QOJscf3S0Q/FpKcMEwVtl2dfbYMxnJILRQ19vH9PUYMj3uHt3C5+/D60b7FQGp8dNEC2fA1CzqQ2czCsWStDjYJVgp1kDl/FQrqnwu148AQrj6iIZehwlFJecXZKzbyC7HKEocIu1dPpLF/oG8aMuc3b89iCeANsfE6HvbUg6MTuWqy1kQR2GZ0cX/O4D8Oowxbk88EHqrh3fdnfVxZEtFvHKj9CodSxdNrU6gMU8NaeZuy0b6A/DnAlp3OMent7dcrQTpuuPy3QYYU86Wy8lJrAywQ3INK3QmyqOzWQsxpl2/y2owLVtHOtu47stn8VQuf6T9lpAXm4EO5yUTiO/SACkv1ZpsHfO4JcEBxNuhOPGI8SRhlEfLTtNRKJs/EIlpalp/q3JEGtKfb3vr/eGB62+FGephcEHppPOS/AbMvWWnN1KrSDSZ6iquET780LFhW/fwhoBiik2T9XG2pulEwu/OQ2V0a6yA1eLmCLttHfaL0mOrxzkUFTy9dqxjUy2HAeUpobQ0Ba3eEREDNxX1yE5TCBWnG8nW2wMPXWpVyMe1OpHLmc/OT76LTkH0EGbDfXk8=
  bucket: terraformapply.com
  region: eu-west-1
  skip_cleanup: true
  local-dir: dist
  acl: public_read
  on:
    repo: arkaitzgarro/ping-pong-counter
    branch: master
